/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as BagRouteImport } from './routes/bag'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/sale': typeof SaleRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/sale': typeof SaleRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/bag': typeof BagRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/sale': typeof SaleRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atelier'
    | '/bag'
    | '/contact'
    | '/craft'
    | '/sale'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collections/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atelier'
    | '/bag'
    | '/contact'
    | '/craft'
    | '/sale'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collections'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atelier'
    | '/bag'
    | '/contact'
    | '/craft'
    | '/sale'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collections/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtelierRoute: typeof AtelierRoute
  BagRoute: typeof BagRoute
  ContactRoute: typeof ContactRoute
  CraftRoute: typeof CraftRoute
  SaleRoute: typeof SaleRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtelierRoute: AtelierRoute,
  BagRoute: BagRoute,
  ContactRoute: ContactRoute,
  CraftRoute: CraftRoute,
  SaleRoute: SaleRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
